### ISSUE TITLE
[TaskScheduler] Идея

### ISSUE THREAD

**Issue by pavel-b-novikov** [denis-bunakalya/nsudotnet#10]
... хорошая. Хитро. Я даже готов вам зачесть задачу без дополнительных придирок.

Позвольте только узнать, как вы собираетесь отменять, скажем, неверно расписанные задачи?

**Comment by denis-bunakalya** [comment]
через RegisteredWaitHandle.Unregister - добавил

**Comment by pavel-b-novikov** [comment]
Зачтено. Поздравляю, вы сломали нашу задачу. На следующий год её уже не будет.
