### ISSUE TITLE
[NumberGuesser] Конкатенация

### ISSUE THREAD

**Issue by pavel-b-novikov** [denis-bunakalya/nsudotnet#2]
> name + ", you are " + Insults[random.Next(4)]

Тру-шарписты не пользуются плюсиками в таких случаях. Объясните почему, поправьте, покайтесь - обязательно.

**Comment by denis-bunakalya** [comment]
на каждый + создаётся новый string, т.е. это занимает больше памяти и работает медленнее, чем например String.Concat, исправил
