### ISSUE TITLE
[NumberGuesser] Обработка исключений

### ISSUE THREAD

**Issue by pavel-b-novikov** [denis-bunakalya/nsudotnet#3]
> try { ... attempt = int.Parse(input); ... } catch(...) {...}

Это СЛИШКОМ тяжелый (как по памяти, так и по времени) способ определения случая, когда текст не представляет собой число. Поищите среди статических методов int-а другой способ.

**Comment by denis-bunakalya** [comment]
int.TryParse, исправил
