### ISSUE TITLE
[NumberGuesser] TimeSpan

### ISSUE THREAD

**Issue by pavel-b-novikov** [denis-bunakalya/nsudotnet#4]
> "Time: " + timeSpan.Minutes + "m " + timeSpan.Seconds + "s"

Мало того что этот код с плюсиками (которых тут отродясь быть не должно), так он еще и выводит неправильные результаты, если пользователь играет больше часа. Объясните что не так, исправьтесь.

**Comment by denis-bunakalya** [comment]
.Minutes возвращает компонент минут, а нужно всё время в минутах, исправил на целую часть от .TotalMinutes
