### ISSUE TITLE
[Calendar] Дни недели - продолжение

### ISSUE THREAD

**Issue by pavel-b-novikov** [denis-bunakalya/nsudotnet#6]
> (position == 5) || (position == 6)

А вот а что мешает использовать-таки .DayOfWeek дальше?

**Comment by denis-bunakalya** [comment]
ничего, исправил

**Comment by pavel-b-novikov** [comment]
>  DateTime dayOfWeek = new DateTime(2016, 04, 11);

Лол. Не делайте так в привычных обществах, но я закрою глаза. 
Это называется "магическая константа", еслишо.
