### ISSUE TITLE
[Calendar] Date.TryPasrse

### ISSUE THREAD

**Issue by pavel-b-novikov** [denis-bunakalya/nsudotnet#7]
> DateTime.TryParse(Console.ReadLine(), out inputDate)

А вот в каком формате-то надо вводить дату, чтобы это начало работать, м?

**Comment by denis-bunakalya** [comment]
в принципе в любом парсится. Вы имеет в виду, что лучше сообщить пользователю в каком формате он может ввести дату? Например (dd.mm.yyyy) - добавил.

**Comment by pavel-b-novikov** [comment]
Ну предположим. 
Попробуйте поменять на своем компьютере локаль в панели управления и запустить вашу программу. Доложите о результатах.
