### ISSUE TITLE
[LinesCounter] Фэйспалм фейспалмов

### ISSUE THREAD

**Issue by pavel-b-novikov** [denis-bunakalya/nsudotnet#8]
А то есть многострочные комментарии 

```
/**
* вот такие вот например
*/
```

не поддерживаются? 

Чет слабенькая какая-то программка.

**Comment by denis-bunakalya** [comment]
теперь поддерживаются

**Comment by pavel-b-novikov** [comment]
> s.Substring(lastCommentBeginning + 2).LastIndexOf("*/")

Вы считаете это нормальным? Посмотрите в MSDN-е описание LastIndexOf и побейте себя самостоятельно за использование Substring там, где он не нужен

**Comment by denis-bunakalya** [comment]
исправил
