### ISSUE TITLE
[LinesCounter] s != string.Empty

### ISSUE THREAD

**Issue by pavel-b-novikov** [denis-bunakalya/nsudotnet#9]
Вот сразу отучайтесь использовать такую конструкцию. Замените на более подходящую

**Comment by denis-bunakalya** [comment]
заменил на s.Length != 0

**Comment by pavel-b-novikov** [comment]
Ай.. ладно. Вам прощаю, но на будущее - используйте для таких случаев метод string.IsNullOrEmpty
